version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  flask_app:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/HospitalDB
    depends_on:
      - mongodb

volumes:
  mongo-data:
